### ISSUE TITLE
free() on uninitialized pointer in GRSTx509MakeProxyCert()

### ISSUE THREAD

**Issue by sustr4** [CESNET/gridsite#15]
As investigate by Alvise and Zdenek in https://ggus.eu/index.php?mode=ticket_info&ticket_id=104009, there is a problem in grst_canl_x509.c, where X509 **certs is properly initialized to NULL, but then certs[0] or certs[i] is referenced, possibly without initialization.

**Comment by valtri** [comment]
Fix released at June 2014.
