### ISSUE TITLE
Support for PUSP proxy certificates

### ISSUE THREAD

**Issue by arax** [CESNET/gridsite#24]
PUSP -- Per-User Sub-Proxy [1]

PUSP proxies should be correctly identified by `gridsite` (according to requirements in [1]) and collected information provided for further processing. This should include basic support in `mod_gridsite` as well.

Information provided to underlying applications must include:
- PUSP detected `YES`/`NO`
- Robot certificate DN
- PUSP certificate DN (Per-User DN = Robot DN + Per-User CN)

[1] https://wiki.egi.eu/wiki/Fedcloud-tf:WorkGroups:Federated_AAI:per-user_sub-proxy

**Comment by valtri** [comment]
Released in 2.3.2 (commit c745836aba666072039c39e7c8a418d629071b60).
